### ISSUE TITLE
Support basic auth for non-Cloud JIRA

### ISSUE THREAD

**Issue by jdpribula** [junipdewan/jirax#4]
On-prem and self-hosted versions of JIRA do not have the feature to create JIRA tokens. It would be great if you were able to support auth via username and password as an option.

**Comment by junipdewan** [comment]
@jdpribula  As per my knowledge JIRA has deprecated the normal JIRA basic auth using passoword and username..I will confirm and update you ..

**Comment by junipdewan** [comment]
@jdpribula  Here that I found
[Deprecation Of Basic Auth](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/)

**Comment by junipdewan** [comment]
> @jdpribula Here that I found
> [Deprecation Of Basic Auth](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/)
> 
> Let me explore once is there any option available out there for self-hosted JIRA versions
> if you have any suggestion or information please let me know . I will try to solve this ASAP.
> Thanks for using and raising your concern

No Support found for non-cloud JIRA basic auth login
